# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: National Week of Making
email: weekofmaking@pif.gov
description: "The National Week of Making focuses on people around the country who are tinkerers, makers, and creatives who share their work with the world."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weekofmaking.pif.gov" # the base hostname & protocol for your site
twitter_username: NaitonofMakers

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE.md
  - about.yml
  - system-security-plan.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
