# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: National Week of Making
email: weekofmaking@pif.gov
description: "On June 17, The White House is kicking off the National Week of Making. This weeek long event celebrates the people all over the country who create and share."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://week-of-making.pif.gov" # the base hostname & protocol for your site
twitter_username: nationofmakers

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE.md
  - about.yml
  - system-security-plan.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
